version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    user: root
    network_mode: host
    restart: always
#    env_file:
#      - .env
#    ports:
#        - "5672:5672"
#        - "15672:15672"
#    networks:
#        - rabbitmq_go_net

#networks:
#  rabbitmq_go_net:
#    driver: bridge
