version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production_nginx
    network_mode: "host"
    volumes:
      - /home/anhbt/Documents/bucket/home_manager/camera/static:/static
      - /home/anhbt/Documents/bucket/home_manager/camera/media:/media
