version: '3'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - .:/app
    environment:
      MYSQL_ROOT_PASSWORD: "admin123"
      MYSQL_DATABASE: "chipchip"
      MYSQL_USER: "anhbt"
      MYSQL_PASSWORD: "admin123"
    restart: always
